spring:
  jpa:
    database: mysql
    show-sql: true
    
    hibernate:
      ddl-auto: none
      
  datasource:
    url: jdbc:mysql://localhost:3306/demo_0
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
jdbc:
    url: jdbc:mysql://localhost:3306/demo_0
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver